name: serving junit report
on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  get_junit_reports:
    name: serving junit reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4.0.4
        with:
          report_paths: '**/*.xml'
          token: ${{ github.token }}
  get_junit_report_in_terminal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Busted
        uses: lunarmodules/busted@v2.2.0
        with:
          args: spec/*.spec.lua --output=junit --output junit
